In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1,NA,3.5,NA,7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],
                    [NA,NA,NA],[NA,6.5,3.]])

In [12]:
cleaned = data.dropna()

In [13]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
df = pd.DataFrame(np.random.randn(7,3))

In [22]:
df.iloc[:4,1]=NA

In [23]:
df.iloc[:2,2] = NA

In [24]:
df

0         1         2
0  0.241659       NaN       NaN
1  0.074460       NaN       NaN
2  0.539035       NaN -0.038750
3  1.134827       NaN  1.638645
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [25]:
df.dropna()

0         1         2
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [26]:
df.dropna(thresh=2)

0         1         2
2  0.539035       NaN -0.038750
3  1.134827       NaN  1.638645
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [27]:
df.fillna(0)

0         1         2
0  0.241659  0.000000  0.000000
1  0.074460  0.000000  0.000000
2  0.539035  0.000000 -0.038750
3  1.134827  0.000000  1.638645
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [28]:
df.fillna({1:0.5,2:0})

0         1         2
0  0.241659  0.500000  0.000000
1  0.074460  0.500000  0.000000
2  0.539035  0.500000 -0.038750
3  1.134827  0.500000  1.638645
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [29]:
_ = df.fillna(0,inplace=True)

In [30]:
df

0         1         2
0  0.241659  0.000000  0.000000
1  0.074460  0.000000  0.000000
2  0.539035  0.000000 -0.038750
3  1.134827  0.000000  1.638645
4 -0.079831 -1.562142  0.943266
5  0.411768 -0.488331 -0.621586
6 -1.739904 -0.084521  1.937172

In [31]:
df = pd.DataFrame(np.random.randn(6,3))

In [32]:
df.iloc[2:,1] = NA

In [33]:
df.iloc[4:,2] = NA

In [34]:
df

0         1         2
0  0.099030  0.735092  0.994418
1  1.723905 -2.119572  0.716004
2  1.047704       NaN  0.271463
3  1.687071       NaN -0.605754
4 -0.033931       NaN       NaN
5 -1.276640       NaN       NaN

In [35]:
df.fillna(method='ffill')

0         1         2
0  0.099030  0.735092  0.994418
1  1.723905 -2.119572  0.716004
2  1.047704 -2.119572  0.271463
3  1.687071 -2.119572 -0.605754
4 -0.033931 -2.119572 -0.605754
5 -1.276640 -2.119572 -0.605754

In [36]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.099030  0.735092  0.994418
1  1.723905 -2.119572  0.716004
2  1.047704 -2.119572  0.271463
3  1.687071 -2.119572 -0.605754
4 -0.033931       NaN -0.605754
5 -1.276640       NaN -0.605754

In [37]:
data = pd.Series([1.,NA,3.5,NA,7])

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [39]:
data = pd.DataFrame({'k1': ['one','two']*3 + ['two'],
                    'k2': [1,1,2,3,3,4,4]})

In [40]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [41]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
data['v1'] = range(7)

In [44]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [45]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [46]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon',
                            'Pastrami','corned beef','Bacon',
                            'pastrami','honey ham','nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [47]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [48]:
meat_to_animal ={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [50]:
lowercased = data['food'].str.lower()

In [51]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [52]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [53]:
data['food'].map(lambda x:meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [54]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])

In [55]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])

In [60]:
transform = lambda x: x[:4].upper()

In [61]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [62]:
Index(['OHIO','COLO','NEW'],dtype='object')

NameError: name 'Index' is not defined

In [66]:
data.index = data.index.map(transform)


In [67]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [68]:
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [69]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [70]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [71]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [72]:
bins = [18,25,35,60,100]

In [73]:
cats = pd.cut(ages,bins)

In [74]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [75]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [76]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [78]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [79]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [80]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']

In [81]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [82]:
data = np.random.rand(20)

In [83]:
pd.cut(data,4,precision=2)

[(0.69, 0.91], (0.69, 0.91], (0.69, 0.91], (0.048, 0.26], (0.048, 0.26], ..., (0.048, 0.26], (0.48, 0.69], (0.48, 0.69], (0.26, 0.48], (0.69, 0.91]]
Length: 20
Categories (4, interval[float64]): [(0.048, 0.26] < (0.26, 0.48] < (0.48, 0.69] < (0.69, 0.91]]

In [84]:
data = np.random.randn(1000)

In [85]:
cats = pd.qcut(data,4)

In [86]:
cats

[(-0.73, -0.0102], (-0.73, -0.0102], (-2.987, -0.73], (-0.73, -0.0102], (-0.73, -0.0102], ..., (-0.73, -0.0102], (-0.73, -0.0102], (-0.73, -0.0102], (-2.987, -0.73], (0.724, 3.069]]
Length: 1000
Categories (4, interval[float64]): [(-2.987, -0.73] < (-0.73, -0.0102] < (-0.0102, 0.724] < (0.724, 3.069]]

In [87]:
pd.value_counts(cats)

(0.724, 3.069]      250
(-0.0102, 0.724]    250
(-0.73, -0.0102]    250
(-2.987, -0.73]     250
dtype: int64

In [88]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(-1.281, -0.0102], (-1.281, -0.0102], (-1.281, -0.0102], (-1.281, -0.0102], (-1.281, -0.0102], ..., (-1.281, -0.0102], (-1.281, -0.0102], (-1.281, -0.0102], (-2.987, -1.281], (1.379, 3.069]]
Length: 1000
Categories (4, interval[float64]): [(-2.987, -1.281] < (-1.281, -0.0102] < (-0.0102, 1.379] < (1.379, 3.069]]

In [89]:
data = pd.DataFrame(np.random.randn(1000,4))

In [90]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002689     0.028574     0.028022     0.053333
std       1.015406     0.957021     1.015477     1.043429
min      -3.122009    -2.644053    -2.892317    -3.214791
25%      -0.654671    -0.626748    -0.663437    -0.611824
50%      -0.006420     0.039885     0.036736     0.074121
75%       0.697456     0.674781     0.667061     0.748201
max       3.085922     2.787559     3.137586     3.665972

In [91]:
col = data[2]

In [92]:
col[np.abs(col) > 3]

76     3.137586
118    3.124858
197    3.082983
Name: 2, dtype: float64

In [93]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
76   0.866493 -0.486093  3.137586  0.161792
118  1.973530  1.563879  3.124858 -1.050314
185  1.355617  0.626460  0.498067 -3.214791
197  2.306266  0.098773  3.082983  0.929039
222 -1.028298 -0.213944 -0.556400 -3.148881
447  3.052527 -1.046358 -1.301903  0.713767
509  0.319876 -0.037569  0.673465  3.665972
676  0.261993  0.370198 -0.436196  3.275862
700  3.085922  0.726843  1.770956  2.422469
837 -3.122009 -0.765792  0.905947 -0.712589

In [94]:
data[np.abs(data) > 3] = np.sign(data)*3

In [95]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.002672     0.028574     0.027677     0.052754
std       1.014623     0.957021     1.014444     1.039411
min      -3.000000    -2.644053    -2.892317    -3.000000
25%      -0.654671    -0.626748    -0.663437    -0.611824
50%      -0.006420     0.039885     0.036736     0.074121
75%       0.697456     0.674781     0.667061     0.748201
max       3.000000     2.787559     3.000000     3.000000

In [96]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0 -1.0 -1.0
3  1.0 -1.0 -1.0  1.0
4  1.0  1.0  1.0  1.0

In [97]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))

In [98]:
sampler = np.random.permutation(5)

In [99]:
sampler

array([0, 4, 3, 1, 2])

In [100]:
array([3,1,4,2,0])

NameError: name 'array' is not defined

In [101]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [102]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [103]:
df.sample(n=3)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [104]:
choices = pd.Series([5,7,-1,6,4])

In [105]:
draws = choices.sample(n=10,replace=True)

In [106]:
draws

2   -1
3    6
0    5
4    4
2   -1
0    5
1    7
2   -1
4    4
2   -1
dtype: int64

In [107]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})

In [111]:
dummies = pd.get_dummies(df['key'],prefix='key')

In [112]:
df_with_dummy = df[['data1']].join(dummies)

In [113]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [114]:
mnames = ['movie_id','title','genres']

In [116]:
movies = pd.read_table('datasets/movielens/movies.dat',sep='::',
                      header=None,names=mnames)

/Users/liu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead.
  
/Users/liu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [117]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [118]:
all_genres = []

In [119]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [120]:
genres = pd.unique(all_genres)

In [121]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [122]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [123]:
dummies = pd.DataFrame(zero_matrix,columns=genres)

In [124]:
gen = movies.genres[0]

In [125]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [126]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [127]:
for i,gen in enumerate(movies.genres):
    indices= dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [128]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [129]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [130]:
np.random.seed(12345)

In [131]:
values = np.random.rand(10)

In [132]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [133]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [134]:
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [135]:
val = 'a,b, guido'

In [136]:
val.split(',')

['a', 'b', ' guido']

In [137]:
pieces = [x.strip() for x in val.split(',')]

In [139]:
[pieces]

[['a', 'b', 'guido']]

In [140]:
first,second,third = pieces

In [141]:
first + '::' + second + '::' + third

'a::b::guido'

In [142]:
'::'.join(pieces)

'a::b::guido'

In [143]:
'guido' in val

True

In [144]:
val.index(',')

1

In [145]:
val.find(':')

-1

In [146]:
val.index(':')

ValueError: substring not found

In [148]:
val.count(',')

2

In [150]:
import re

In [151]:
text = "foo  bar\t baz  \tqux"

In [152]:
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [155]:
regex = re.compile('\s+')

In [156]:
regex.findall(text)

['  ', '\t ', '  \t']

In [158]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [159]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [160]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [161]:
m = regex.search(text)

In [162]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [163]:
text[m.start():m.end()]

'dave@google.com'

In [164]:
print(regex.match(text))

None


In [165]:
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [166]:
pattern = r'[A-Z0-9._%+-])@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [167]:
regex = re.compile(pattern,flags=re.IGNORECASE)

error: unbalanced parenthesis at position 13

In [168]:
m = regex.match('wesm@bright.net')

In [169]:
m.groups()

()

In [170]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [171]:
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com',
       'Rob':'rob@gmail.com','Wes':np.nan}

In [172]:
data = pd.Series(data)

In [173]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [174]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [175]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [176]:
pattern

'[A-Z0-9._%+-])@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [177]:
data.str.findall(pattern,flags=re.IGNORECASE)

error: unbalanced parenthesis at position 13

In [178]:
matches

NameError: name 'matches' is not defined