In [3]:
import pandas as pd

In [4]:
from pandas import Series,DataFrame

In [5]:
obj = pd.Series([4,7,-5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3])

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj.values

array([ 4,  7, -5,  3])

In [11]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [15]:
obj2['d']

4

In [16]:
 obj2['d'] = 6

In [17]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [18]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [19]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [21]:
import numpy as np

In [22]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [23]:
'b' in obj2

True

In [24]:
'e' in obj2

False

In [25]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [26]:
obj3 = pd.Series(sdata)

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
states = ['California','Ohio','Oregon','Texas']

In [29]:
obj4 = pd.Series(sdata,index = states)

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [33]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [35]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [37]:
obj4.name = 'population'

In [38]:
obj4.index.name='state'

In [39]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [40]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [42]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [44]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year': [2000,2001,2002,2001,2002,2003],
       'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [45]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [47]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index=['one','two','three','four',
                           'five','six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [54]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 16.5

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [58]:
frame2['debt'] = np.arange(6.)

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [60]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [61]:
frame2['debt'] = val

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [63]:
frame2['eastern'] = frame2.state == 'Ohio'

In [64]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [65]:
del frame2['eastern']

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [67]:
pop = {'Nevada': {2001:2.4,2002:2.9},
      'Ohio': {2000:1.5,2001:1.7,2002:3.6}}

In [68]:
frame3 = pd.DataFrame(pop)

In [69]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [70]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [71]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [73]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [74]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [75]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [76]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [77]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [78]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [79]:
obj = pd.Series(range(3), index=['a','b','c'])

In [80]:
index = obj.index

In [81]:
index

Index(['a', 'b', 'c'], dtype='object')

In [82]:
index[1:]

Index(['b', 'c'], dtype='object')

In [83]:
labels = pd.Index(np.arange(3))

In [84]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [85]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [86]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [87]:
obj2.index is labels

True

In [88]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [89]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [90]:
'Ohio' in frame3.columns

True

In [92]:
2003 in frame3.index

False

In [93]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [94]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [95]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [96]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [97]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [98]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [101]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [102]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','b','d'],
                    columns=['Ohio','Texas','California'])

In [104]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [105]:
frame2 = frame.reindex(['a','b','c','d'])

In [106]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   NaN    NaN         NaN
d   6.0    7.0         8.0

In [107]:
states = ['Texas','Utah','California']

In [108]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
d      7   NaN           8

In [110]:
frame.loc[['a','b','c','d'],states]

/Users/liu/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    4.0   NaN         5.0
c    NaN   NaN         NaN
d    7.0   NaN         8.0

In [111]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [112]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [113]:
new_obj = obj.drop('c')

In [114]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [115]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [116]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','New Rork'],
                    columns=['one','two','three','four'])

In [117]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New Rork   12   13     14    15

In [118]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New Rork   12   13     14    15

In [119]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New Rork   12     14    15

In [120]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New Rork   12     14

In [121]:
obj.drop('c',inplace=True)

In [122]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [123]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])

In [124]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [125]:
obj['b']

1.0

In [126]:
obj[1]

1.0

In [127]:
ser = pd.Series(np.arange(3.))

In [128]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [129]:
ser[-1]

KeyError: -1

In [130]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [131]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])

In [132]:
frame

b         d         e
Utah   -2.215590  0.213736 -2.293147
Ohio   -0.469029  1.392542 -0.121064
Texas  -0.223301 -1.289234 -0.904637
Oregon  0.971013  0.879921 -0.568154

In [133]:
np.abs(frame)

b         d         e
Utah    2.215590  0.213736  2.293147
Ohio    0.469029  1.392542  0.121064
Texas   0.223301  1.289234  0.904637
Oregon  0.971013  0.879921  0.568154

In [134]:
f = lambda x: x.max() - x.min()

In [135]:
frame.apply(f)

b    3.186602
d    2.681775
e    2.172083
dtype: float64

In [136]:
frame.apply(f,axis='columns')

Utah      2.506883
Ohio      1.861571
Texas     1.065933
Oregon    1.539167
dtype: float64

In [137]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [138]:
frame.apply(f)

b         d         e
min -2.215590 -1.289234 -2.293147
max  0.971013  1.392542 -0.121064

In [139]:
format = lambda x: '%.2f' % x

In [140]:
frame.applymap(format)

b      d      e
Utah    -2.22   0.21  -2.29
Ohio    -0.47   1.39  -0.12
Texas   -0.22  -1.29  -0.90
Oregon   0.97   0.88  -0.57

In [141]:
frame['e'].map(format)

Utah      -2.29
Ohio      -0.12
Texas     -0.90
Oregon    -0.57
Name: e, dtype: object

In [142]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [143]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [144]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])

In [145]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [146]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4